version: "3.8"

services:
  web:
    image: "nginx:alpine"
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    networks:
      - db
    volumes:
      - /app

  worker:
    image: "my-worker-image:latest"
    restart: unless-stopped
    networks:
      - legacy
    volumes:
      - ./data:/worker

  db:
    image: mysql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: on-failure
    networks:
      db:
        aliases:
          - database
      legacy:
        aliases:
          - mysql
    volumes:
      - db:/var/lib/mysql

networks:
  db:
  legacy:

volumes:
  db:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.1,rw"
      device: ":/path/on/nfs"
  demo:
